package lk.ijse.rangabeautysalon.util;

public enum Routes {
    MANAGEEMP_FORM, MANAGECUSTOMER_FORM, MAKEPAYMENT_FORM, MANAGEPRODUCT_FORM, SIGNUP_FORM, SIGNIN_FORM, LOGIN_FORM, APPOINTMENT_FORM,DRESSINGS_FORM,ORDER_FORM,SERVICE_FORM,PRODUCT_FORM,SUPPLIER_FORM
}
