package lk.ijse.rangabeautysalon.service;

public enum ServiceTypes {
    APPOINTMENT,CUSTOMER,DRESSINGAPPOINTMENT,DRESSING,EMPLOYEE,EXTRAEXPENSE,ORDER,ORDERPRODUCT,PAYMENT,PRODUCT,REGISTRATION,SALONSAPPOINTMENT,SALONSERVICE,APPOINTMENTTM

}
