package lk.ijse.rangabeautysalon.dao;

public enum DaoTypes {
    APPOINTMENT,CUSTOMER,DRESSINGAPPOINTMENT,DRESSING,EMPLOYEE,EXTRAEXPENSE,ORDER,ORDERPRODUCT,PAYMENT,PRODUCT,REGISTRATION,SALONSAPPOINTMENT,SALONSERVICE,APPOINTMENTTM
}
